name: Race Check

on:

  workflow_dispatch:

  schedule:
    - cron: '0 11 * * *'

jobs:

  check-races:*
    runs-on: ubuntu-latest

    p*rmissions:
      contents: write

*   steps:

      - uses: actions/c*eckout@v4

      - uses: actions/s*tup-python@v5
        with:
      *   python-version: '3.11'

      -*run: pip install requests

- run: python monitor.py
  env:
    EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
    EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      - name: Save Status File

        run: *
          git config user.name gi*hub-actions
          git config u*er.email github-actions@github.com*
          git add status.json

  *       git diff --cached --quiet |* git commit -m "Update status"

  *       git push
